apiVersion: apps/v1
kind: Deployment
metadata:
  name: shenlong-deployment
  labels:
    app: shenlong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shenlong
  template:
    metadata:
      labels:
        app: shenlong
    spec:
      containers:
      - name: shenlong
        image: docker.io/mariovalente/shenlong:latest
        ports:
        - containerPort: 3001
        env:
        - name: INGRESS_READY
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: shenlong-service
spec:
  selector:
    app: shenlong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
---


